### ISSUE TITLE
Support Jekyll 4.x

### ISSUE THREAD

**Issue by SUPERCILEX** [benbalter/jekyll-default-layout#11]
This line https://github.com/benbalter/jekyll-default-layout/blob/9916edef5187069df00bb705f972baaa8594b58c/jekyll-default-layout.gemspec#L19 is blocking an upgrade to Jekyll. If the plugin is compatible can we change it to something like `"jekyll", ">= 3.7", "< 5.0"`?

**Comment by benbalter** [comment]
@SUPERCILEX Thanks. If you submit a pull request, I'd be glad to review and get a new release out.

**Comment by 2martens** [comment]
Hey, it is cool that the GitHub source code now supports this but there is still no new version on RubyGems so it cannot be installed. Could you make a release with these changes?
