### ISSUE TITLE
Support for HAML (or other renderers in general?)

### ISSUE THREAD

**Issue by alexanderadam** [benbalter/jekyll-default-layout#13]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I would like to use `jekyll-default-layout` together with [jekyll-haml-markup](https://github.com/afaundez/jekyll-haml-markup)

### Describe the solution you'd like

It should work

### Describe alternatives you've considered

Using Markdown, I guess?

### Additional context

Well, it's not working with `.haml` files.

**Comment by benbalter** [comment]
@alexanderadam Thanks for opening this issue. This isn't something I'd be interested, as I don't use the HAML plugin you linked to, but if it can be implemented without adding too much additional complexity, I'd glad to review a pull request that adds support for it.

**Comment by alexanderadam** [comment]
Nevermind. I switched to middleman. :wink:
