### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by SUPERCILEX** [benbalter/jekyll-default-layout#14]
@benbalter gentle bump. A new release would be much appreciated to support Jekyll 4.x (#11).

https://rubygems.org/gems/jekyll-default-layout/versions

**Comment by benbalter** [comment]
Released! https://github.com/benbalter/jekyll-default-layout/releases/tag/v0.1.5

**Comment by SUPERCILEX** [comment]
Thank you!!!
