### ISSUE TITLE
Also apply default layout to Collections

### ISSUE THREAD

**Issue by SteGriff** [benbalter/jekyll-default-layout#3]
Hi Ben!

Thanks for the great plugin. I just got into Jekyll and this has made it really easy to write simple sites that anyone can edit without messing it up!

On my site I have some collections which are set to `output : true` but they don't implicitly get the default layout (they end up with no layout). I tried hacking the plugin myself to add collections into the `documents` list:

    def documents
      [site.pages, site.posts.docs, site.collections.docs].flatten
    end

But I'm new to ruby and jekyll so I think I made a bad assumption about the data types or API involved; the error says theree is no `docs` on `collections` (it looked from the [source for collections.rb][colrb] like there was...)

If this would be easy to implement it would add tons of value for me (hopefully others?) or if you could point me in the right direction to hack my own fork that would also be tremendous 👍 

Thanks again,
Ste

[colrb]: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/collection.rb

**Comment by benbalter** [comment]
This plugin is not currently intended to work with collections, only pages. If you'd like to apply a default layout to all documents in a collection, you can use [front matter defaults](https://jekyllrb.com/docs/configuration/#front-matter-defaults).

**Comment by SteGriff** [comment]
That's a great tip, thank you :)

**Comment by cbarrick** [comment]
What's the rationale for not supporting collections?
